export const PHASES = Object.freeze({
  LOBBY: 'LOBBY',
  NIGHT: 'NIGHT',
  DAY_DISCUSSION: 'DAY_DISCUSSION',
  DAY_VOTING: 'DAY_VOTING',
  DEFENSE_STAGE: 'DEFENSE_STAGE',
  LAST_WORDS: 'LAST_WORDS',
  GAME_OVER: 'GAME_OVER',
});

export const ROLES = Object.freeze({
  MAFIA_BOSS: 'MAFIA_BOSS',
  SILENCER: 'SILENCER',
  MAYOR: 'MAYOR',
  GOOD_BOY: 'GOOD_BOY',
  MEDIC: 'MEDIC',
  SNIPER: 'SNIPER',
  CITIZEN: 'CITIZEN',
  // Dynamic-matrix roles
  MAFIOSO: 'MAFIOSO',
  FRAMER: 'FRAMER',
  DETECTIVE: 'DETECTIVE',
  VIGILANTE: 'VIGILANTE',
  JOKER: 'JOKER',
});

export const TEAMS = Object.freeze({
  MAFIA: 'MAFIA',
  TOWN: 'TOWN',
  NEUTRAL: 'NEUTRAL',
});

export const ROLE_TEAMS = Object.freeze({
  MAFIA_BOSS: TEAMS.MAFIA,
  SILENCER: TEAMS.MAFIA,
  MAYOR: TEAMS.TOWN,
  GOOD_BOY: TEAMS.TOWN,
  MEDIC: TEAMS.TOWN,
  SNIPER: TEAMS.TOWN,
  CITIZEN: TEAMS.TOWN,
  MAFIOSO: TEAMS.MAFIA,
  FRAMER: TEAMS.MAFIA,
  DETECTIVE: TEAMS.TOWN,
  VIGILANTE: TEAMS.TOWN,
  JOKER: TEAMS.NEUTRAL,
});

export const NIGHT_ABILITIES = Object.freeze({
  MAFIA_BOSS: 'KILL',
  SILENCER: 'SILENCE',
  MEDIC: 'SAVE',
  SNIPER: 'SHOOT',
  FRAMER: 'FRAME',
  DETECTIVE: 'INVESTIGATE',
  VIGILANTE: 'SHOOT',
});

export const VOTE_WEIGHTS = Object.freeze({
  BASE: 1,
  MAYOR_REVEALED: 3,
  SILENCED: 0,
});

export const LIMITS = Object.freeze({
  MIN_PLAYERS: 4,
  MAX_PLAYERS: 12,
  NAME_MIN: 2,
  NAME_MAX: 16,
});

export const DEATH_CAUSES = Object.freeze({
  MAFIA_KILL: 'MAFIA_KILL',
  SNIPER_SHOT: 'SNIPER_SHOT',
  SNIPER_BACKFIRE: 'SNIPER_BACKFIRE',
  GOOD_BOY_REVENGE: 'GOOD_BOY_REVENGE',
  VOTE_ELIMINATION: 'VOTE_ELIMINATION',
});
