'use client';

import { useState } from 'react';
import { Clock3, Crown, Loader2, Minus, Plus, Shield, Users, X } from 'lucide-react';
import type { RoomSettingsState } from '@/lib/types';
import { LIMITS_HINT_MAX, LIMITS_HINT_MIN } from '@/lib/constants';

const DEFAULTS: RoomSettingsState = { targetPlayerCount: 6, mafiaCount: 1, effectiveMafiaCount: 1, maxMafiaCount: 2, timers: { nightMs: 45_000, discussionMs: 90_000, votingMs: 45_000, defenseMs: 30_000, lastWordsMs: 20_000 }, voting: { mayorWeight: 3, tiePolicy: 'NO_EXECUTION' } };

export function CustomRoomModal({ open, busy, onClose, onCreate }: { open: boolean; busy: boolean; onClose: () => void; onCreate: (settings: RoomSettingsState) => void }) {
  const [settings, setSettings] = useState(DEFAULTS);
  if (!open) return null;
  const players = settings.targetPlayerCount ?? 6;
  const maxMafia = Math.max(1, Math.min(4, Math.floor((players - 1) / 2)));
  const setTimer = (key: keyof RoomSettingsState['timers'], seconds: number) => setSettings((current) => ({ ...current, timers: { ...current.timers, [key]: seconds * 1000 } }));
  return <div className="fixed inset-0 z-[110] flex items-end justify-center bg-black/85 backdrop-blur-sm sm:items-center sm:p-4" dir="rtl"><section className="max-h-[96dvh] w-full max-w-4xl overflow-y-auto rounded-t-3xl border border-gold-500/30 bg-[#090b12] shadow-2xl sm:rounded-3xl">
    <header className="sticky top-0 z-10 flex items-center justify-between border-b border-white/10 bg-[#090b12]/95 p-4 backdrop-blur"><div><h2 className="text-xl font-black text-white">غرفة مخصصة</h2><p className="text-xs text-slate-400">ابنِ قواعد الجولة بالتفصيل</p></div><button onClick={onClose} disabled={busy} className="rounded-xl border border-white/10 p-2"><X className="h-5 w-5" /></button></header>
    <div className="grid gap-4 p-4 lg:grid-cols-[1fr_280px]">
      <div className="space-y-4">
        <Section icon={<Users />} title="تكوين الغرفة"><div className="grid gap-3 sm:grid-cols-2"><Stepper label="عدد اللاعبين" value={players} min={LIMITS_HINT_MIN} max={LIMITS_HINT_MAX} onChange={(value) => setSettings((current) => ({ ...current, targetPlayerCount: value, mafiaCount: Math.min(current.mafiaCount ?? 1, Math.max(1, Math.floor((value - 1) / 2))) }))} /><Stepper label="عدد المافيا" value={settings.mafiaCount ?? 1} min={1} max={maxMafia} onChange={(value) => setSettings((current) => ({ ...current, mafiaCount: value }))} /></div></Section>
        <Section icon={<Clock3 />} title="مؤقتات المراحل"><div className="grid gap-3 sm:grid-cols-2">{([['nightMs','الليل'],['discussionMs','النقاش'],['votingMs','التصويت'],['defenseMs','الدفاع'],['lastWordsMs','الكلمات الأخيرة']] as const).map(([key,label]) => <Stepper key={key} label={`${label} (ث)`} value={settings.timers[key] / 1000} min={10} max={300} step={5} onChange={(value) => setTimer(key, value)} />)}</div></Section>
        <Section icon={<Crown />} title="قواعد التصويت"><div className="grid gap-3 sm:grid-cols-2"><SelectCard label="وزن صوت العمدة" value={String(settings.voting.mayorWeight)} options={[['1','صوت واحد'],['2','صوتان'],['3','3 أصوات']]} onChange={(value) => setSettings((current) => ({ ...current, voting: { ...current.voting, mayorWeight: Number(value) as 1|2|3 } }))} /><SelectCard label="عند التعادل" value={settings.voting.tiePolicy} options={[['NO_EXECUTION','لا إعدام'],['RANDOM_TOP','اختيار عشوائي'],['REVOTE','إعادة التصويت']]} onChange={(value) => setSettings((current) => ({ ...current, voting: { ...current.voting, tiePolicy: value as RoomSettingsState['voting']['tiePolicy'] } }))} /></div></Section>
      </div>
      <aside className="h-fit rounded-3xl border border-gold-500/25 bg-gradient-to-b from-gold-500/10 to-transparent p-4 lg:sticky lg:top-24"><div className="mb-4 flex items-center gap-2 text-gold-200"><Shield className="h-5 w-5" /><h3 className="font-black">ملخص الإعدادات</h3></div><dl className="space-y-3 text-xs">{[['اللاعبون',players],['المافيا',settings.mafiaCount],['الليل',`${settings.timers.nightMs/1000}ث`],['النقاش',`${settings.timers.discussionMs/1000}ث`],['التصويت',`${settings.timers.votingMs/1000}ث`]].map(([label,value]) => <div key={String(label)} className="flex justify-between border-b border-white/10 pb-2"><dt className="text-slate-400">{label}</dt><dd className="font-black text-white">{value}</dd></div>)}</dl><p className="mt-4 text-[10px] leading-5 text-slate-500">تُراجع القيود مرة أخرى داخل المحرك قبل إنشاء الغرفة.</p><button disabled={busy} onClick={() => onCreate({ ...settings, effectiveMafiaCount: settings.mafiaCount ?? 1, maxMafiaCount: maxMafia })} className="mt-5 flex min-h-12 w-full items-center justify-center gap-2 rounded-2xl bg-gradient-to-l from-blood-700 to-blood-600 font-black text-white shadow-lg disabled:opacity-50">{busy && <Loader2 className="h-4 w-4 animate-spin" />}إنشاء الغرفة المخصصة</button></aside>
    </div>
  </section></div>;
}

function Section({ icon, title, children }: { icon: React.ReactNode; title: string; children: React.ReactNode }) { return <section className="rounded-3xl border border-white/10 bg-white/[.035] p-4"><h3 className="mb-4 flex items-center gap-2 font-black text-gold-100"><span className="text-gold-400">{icon}</span>{title}</h3>{children}</section>; }
function Stepper({ label, value, min, max, step = 1, onChange }: { label: string; value: number; min: number; max: number; step?: number; onChange: (value: number) => void }) { return <div className="rounded-2xl border border-white/10 bg-black/25 p-3"><p className="mb-2 text-xs font-bold text-slate-300">{label}</p><div className="flex items-center justify-between"><button onClick={() => onChange(Math.max(min,value-step))} className="grid h-9 w-9 place-items-center rounded-xl bg-white/10"><Minus className="h-4 w-4" /></button><strong className="text-lg text-white">{value}</strong><button onClick={() => onChange(Math.min(max,value+step))} className="grid h-9 w-9 place-items-center rounded-xl bg-gold-500/15 text-gold-300"><Plus className="h-4 w-4" /></button></div></div>; }
function SelectCard({ label, value, options, onChange }: { label: string; value: string; options: [string,string][]; onChange: (value: string) => void }) { return <label className="rounded-2xl border border-white/10 bg-black/25 p-3 text-xs font-bold text-slate-300"><span className="mb-2 block">{label}</span><select value={value} onChange={(event) => onChange(event.target.value)} className="w-full rounded-xl border border-white/10 bg-night-900 p-3 text-white">{options.map(([key,text]) => <option key={key} value={key}>{text}</option>)}</select></label>; }
